### ISSUE TITLE
无法使用吗，INIT和依赖文件内容都有问题，加载失败

### ISSUE THREAD

**Issue by T8mars** [alimama-creative/SDXL_EcomID_ComfyUI#1]
![image](https://github.com/user-attachments/assets/61267005-926d-41c8-905e-3cb7b2cf746d)

![image](https://github.com/user-attachments/assets/cfcb5bbb-6386-4686-827a-b4af7d9dd34c)

![image](https://github.com/user-attachments/assets/c6584216-22fb-42d9-a0cc-fbfae1c6e5c7)

**Comment by T8mars** [comment]
没事了，不从秋叶包安装，直接GIT CLONE即可，可以关闭本ISSUE了

**Comment by 66-DASHUN** [comment]
我为啥git也不行啊
