### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by T8mars** [alimama-creative/SDXL_EcomID_ComfyUI#3]
1、HF上写着推荐ecomxl.safetensors 这个大模型在哪里下载
2、我尝试了几个方法蒙版换脸都不行，是未支持还是如何，如果已支持能否提供对应工作流参考

**Comment by WenRuxue** [comment]
1、抱歉，自研EcomXL大模型暂未开源，支持其他基于sdxl模型。
2、支持t2i、i2i直接生成，如果仅想换脸，可以尝试和inpaint等controlnet配合使用（推荐我们开源的[EcomXL-Inpainting-ControlNet]（https://huggingface.co/alimama-creative/EcomXL_controlnet_inpaint）和 [EcomXL-Softedge-ControlNet]（https://huggingface.co/alimama-creative/EcomXL_controlnet_softedge））。

1、Sorry, our EcomXL model is not open-source yet, but it supports other models based on SDXL.
2、It supports t2i and i2i for direct generation. If you only want to swap faces, consider using it in combination with inpainting ControlNet (we recommend our open-source [EcomXL-Inpainting-ControlNet](https://huggingface.co/alimama-creative/EcomXL_controlnet_inpaint) and [EcomXL-Softedge-ControlNet](https://huggingface.co/alimama-creative/EcomXL_controlnet_softedge)).

**Comment by WenRuxue** [comment]
感谢您的关注，我们最新公开了仅换脸的workflow，欢迎参考。

Thank you for your attention. We have recently released a face-swapping workflow for public use. Feel free to take a look!
